backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: Hero, name: hero, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Headline, name: headline, widget: string}, {label: Image, name: image, widget: image}]}
